name: Windows Runner Build
on:
  pull_request:
jobs:
  build-containers:
    name: Build Containers
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Build
      run: |
        docker build -f ci/windows_runner/Dockerfile